### ISSUE TITLE
Installed on a synology docker. --> npm ERR!

### ISSUE THREAD

**Issue by Adefx** [mountaindude/verisure-mqtt#15]
Crach error at start : 
npn ERR! missing script: start.

Could be synology docker, since it's not easy to do a compose.yml All done with a gui. 

HEre the environnement variable
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=8.15.1
YARN_VERSION=1.12.3

Host, port pwd username topic and debug has been filled

**Comment by mountaindude** [comment]
Hard to say what's causing it without being able to investigate in more
detail.
I would guess that the rather old Docker version in sue might cause issues.
Just a guess though.

**Comment by Adefx** [comment]
Could be that. 
I tried antother Verisure MQTT docker ----> https://hub.docker.com/r/pyllyukko/verisure-mqtt
and it booted properly. 
Now i must figure out how to check if i receive the verisure data correctly & transmit it to my Mqtt Broker.

**Comment by mountaindude** [comment]
@Adefx 

I've just released v1.2.0, which is built on Node 12 (vs Node 8 in previous versions). All dependencies are updated - might be worth trying it on your Synology again. Worth a shot, I figure..

No new features, just a bunch of general updates.

https://github.com/mountaindude/verisure-mqtt/releases/tag/v1.2.0
